---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost {{ ansible_hostname }}"
    regexp: ^127\.0\.0\.1
  when:
    - ansible_virtualization_type != 'docker'
    - sansible_gocd_server_fix_hostname | bool

- name: Install some dependencies
  become: yes
  apt:
    name: "{{ sansible_gocd_server_packages }}"

- name: Install AWS CLI
  become: yes
  pip:
    name:
      - awscli
      - boto
  when: sansible_gocd_server_aws_install_cli

- name: Download GoCD PGP key (works with Bionic behind a proxy)
  become: yes
  get_url:
    dest: /usr/local/src/gocd.asc
    mode: 0644
    url: "https://{{ sansible_gocd_server_repo_keyserver }}/pks/lookup?op=get&search=0x{{ sansible_gocd_server_repo_key_id }}"

- name: Ensures GoCD PGP key is known
  become: yes
  apt_key:
    file: /usr/local/src/gocd.asc
    id: "{{ sansible_gocd_server_repo_key_id }}"
    state: present

- name: Add GoCD APT repository
  become: yes
  apt_repository:
    repo: "{{ sansible_gocd_server_repo_source }}"
    update_cache: yes

- name: Install go-server
  become: yes
  apt:
    name: "go-server={{ sansible_gocd_server_version | regex_replace('^(.*?)\\*?$', '\\1*') }}"
    state: present
    force: yes

- name: Create various directories
  become: yes
  file:
    group: "{{ sansible_gocd_server_group }}"
    owner: "{{ sansible_gocd_server_user }}"
    path: "/home/{{ sansible_gocd_server_user }}/{{ item }}"
    state: directory
  with_items:
    - .aws
    - bin
    - work/go-server
    - work/go-server/plugins/external
    - work/go-server/artifacts/pipelines

- name: Add go-server to autostart for SysV
  become: yes
  service:
    name: go-server
    enabled: yes
  when: ansible_service_mgr != "systemd"

- name: Add go-server to autostart for SystemD
  become: yes
  systemd:
    enabled: yes
    name: go-server
  when: ansible_service_mgr == "systemd"

- name: Install go-server plugins
  become: yes
  become_user: "{{ sansible_gocd_server_user }}"
  get_url:
    dest: "/home/{{ sansible_gocd_server_user }}/work/go-server/plugins/external"
    url: "{{ item }}"
  with_items: "{{ sansible_gocd_server_plugins }}"
  notify:
    - restart go-server
